name: Health Check URL

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1-23 * * *'
    - cron: '0 0 * * *'
  

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          # Check the following URLs one by one sequentially
          url: https://pokedex1709.herokuapp.com
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: no # Optional, defaults to "no"
       
